# Generated by Django 5.1.15 on 2026-03-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moodsession',
            new_name='fc_mood_ses_user_id_5aadac_idx',
            old_name='fc_mood_ses_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='moodsession',
            new_name='fc_mood_ses_detecte_4b7822_idx',
            old_name='fc_mood_ses_mood_idx',
        ),
    ]
